<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Bandblog', 'doctrine');

/**
 * BaseBandblog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $band_id
 * @property string $band
 * 
 * @method integer  getId()      Returns the current record's "id" value
 * @method integer  getBandId()  Returns the current record's "band_id" value
 * @method string   getBand()    Returns the current record's "band" value
 * @method Bandblog setId()      Sets the current record's "id" value
 * @method Bandblog setBandId()  Sets the current record's "band_id" value
 * @method Bandblog setBand()    Sets the current record's "band" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBandblog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bandblog');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('band_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('band', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}