<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvPromoterCopy', 'doctrine');

/**
 * BaseTvPromoterCopy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $club_id
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $fax
 * @property timestamp $created_at
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getClubId()     Returns the current record's "club_id" value
 * @method string         getName()       Returns the current record's "name" value
 * @method string         getEmail()      Returns the current record's "email" value
 * @method string         getPhone()      Returns the current record's "phone" value
 * @method string         getFax()        Returns the current record's "fax" value
 * @method timestamp      getCreatedAt()  Returns the current record's "created_at" value
 * @method TvPromoterCopy setId()         Sets the current record's "id" value
 * @method TvPromoterCopy setClubId()     Sets the current record's "club_id" value
 * @method TvPromoterCopy setName()       Sets the current record's "name" value
 * @method TvPromoterCopy setEmail()      Sets the current record's "email" value
 * @method TvPromoterCopy setPhone()      Sets the current record's "phone" value
 * @method TvPromoterCopy setFax()        Sets the current record's "fax" value
 * @method TvPromoterCopy setCreatedAt()  Sets the current record's "created_at" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvPromoterCopy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_promoterCopy');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('club_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '4',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 125, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 125,
             ));
        $this->hasColumn('email', 'string', 125, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 125,
             ));
        $this->hasColumn('phone', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fax', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}