<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Links', 'doctrine');

/**
 * BaseLinks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $linkname
 * @property string $url
 * 
 * @method integer getId()       Returns the current record's "id" value
 * @method string  getLinkname() Returns the current record's "linkname" value
 * @method string  getUrl()      Returns the current record's "url" value
 * @method Links   setId()       Sets the current record's "id" value
 * @method Links   setLinkname() Sets the current record's "linkname" value
 * @method Links   setUrl()      Sets the current record's "url" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLinks extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('links');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('linkname', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('url', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 75,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}