<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvAgentRoster', 'doctrine');

/**
 * BaseTvAgentRoster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $agent_id
 * @property integer $artist_id
 * @property integer $agency_id
 * @property TvAgency $TvAgency
 * @property TvAgents $TvAgents
 * @property TvArtist $TvArtist
 * 
 * @method integer       getId()        Returns the current record's "id" value
 * @method integer       getAgentId()   Returns the current record's "agent_id" value
 * @method integer       getArtistId()  Returns the current record's "artist_id" value
 * @method integer       getAgencyId()  Returns the current record's "agency_id" value
 * @method TvAgency      getTvAgency()  Returns the current record's "TvAgency" value
 * @method TvAgents      getTvAgents()  Returns the current record's "TvAgents" value
 * @method TvArtist      getTvArtist()  Returns the current record's "TvArtist" value
 * @method TvAgentRoster setId()        Sets the current record's "id" value
 * @method TvAgentRoster setAgentId()   Sets the current record's "agent_id" value
 * @method TvAgentRoster setArtistId()  Sets the current record's "artist_id" value
 * @method TvAgentRoster setAgencyId()  Sets the current record's "agency_id" value
 * @method TvAgentRoster setTvAgency()  Sets the current record's "TvAgency" value
 * @method TvAgentRoster setTvAgents()  Sets the current record's "TvAgents" value
 * @method TvAgentRoster setTvArtist()  Sets the current record's "TvArtist" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvAgentRoster extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_agent_roster');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('agent_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('artist_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('agency_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TvAgency', array(
             'local' => 'agency_id',
             'foreign' => 'id'));

        $this->hasOne('TvAgents', array(
             'local' => 'agent_id',
             'foreign' => 'id'));

        $this->hasOne('TvArtist', array(
             'local' => 'artist_id',
             'foreign' => 'id'));
    }
}