<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pagecount', 'doctrine');

/**
 * BasePagecount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $page
 * @property integer $count
 * 
 * @method integer   getId()    Returns the current record's "id" value
 * @method string    getPage()  Returns the current record's "page" value
 * @method integer   getCount() Returns the current record's "count" value
 * @method Pagecount setId()    Sets the current record's "id" value
 * @method Pagecount setPage()  Sets the current record's "page" value
 * @method Pagecount setCount() Sets the current record's "count" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePagecount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pagecount');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('page', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('count', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}