<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvClubTickets', 'doctrine');

/**
 * BaseTvClubTickets
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $club_id
 * @property integer $product_code
 * @property string $club
 * @property string $shorturl
 * @property string $longurl
 * @property string $city
 * @property string $state
 * @property string $street
 * @property string $zip
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method integer       getClubId()       Returns the current record's "club_id" value
 * @method integer       getProductCode()  Returns the current record's "product_code" value
 * @method string        getClub()         Returns the current record's "club" value
 * @method string        getShorturl()     Returns the current record's "shorturl" value
 * @method string        getLongurl()      Returns the current record's "longurl" value
 * @method string        getCity()         Returns the current record's "city" value
 * @method string        getState()        Returns the current record's "state" value
 * @method string        getStreet()       Returns the current record's "street" value
 * @method string        getZip()          Returns the current record's "zip" value
 * @method TvClubTickets setId()           Sets the current record's "id" value
 * @method TvClubTickets setClubId()       Sets the current record's "club_id" value
 * @method TvClubTickets setProductCode()  Sets the current record's "product_code" value
 * @method TvClubTickets setClub()         Sets the current record's "club" value
 * @method TvClubTickets setShorturl()     Sets the current record's "shorturl" value
 * @method TvClubTickets setLongurl()      Sets the current record's "longurl" value
 * @method TvClubTickets setCity()         Sets the current record's "city" value
 * @method TvClubTickets setState()        Sets the current record's "state" value
 * @method TvClubTickets setStreet()       Sets the current record's "street" value
 * @method TvClubTickets setZip()          Sets the current record's "zip" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvClubTickets extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_club_tickets');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('club_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('product_code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('club', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('shorturl', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('longurl', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('state', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('street', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('zip', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}