<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Reviews', 'doctrine');

/**
 * BaseReviews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $bandid
 * @property string $band
 * @property string $trackname
 * @property string $mp3
 * @property string $albumname
 * @property integer $track
 * @property string $image
 * @property timestamp $created_at
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method integer   getBandid()     Returns the current record's "bandid" value
 * @method string    getBand()       Returns the current record's "band" value
 * @method string    getTrackname()  Returns the current record's "trackname" value
 * @method string    getMp3()        Returns the current record's "mp3" value
 * @method string    getAlbumname()  Returns the current record's "albumname" value
 * @method integer   getTrack()      Returns the current record's "track" value
 * @method string    getImage()      Returns the current record's "image" value
 * @method timestamp getCreatedAt()  Returns the current record's "created_at" value
 * @method Reviews   setId()         Sets the current record's "id" value
 * @method Reviews   setBandid()     Sets the current record's "bandid" value
 * @method Reviews   setBand()       Sets the current record's "band" value
 * @method Reviews   setTrackname()  Sets the current record's "trackname" value
 * @method Reviews   setMp3()        Sets the current record's "mp3" value
 * @method Reviews   setAlbumname()  Sets the current record's "albumname" value
 * @method Reviews   setTrack()      Sets the current record's "track" value
 * @method Reviews   setImage()      Sets the current record's "image" value
 * @method Reviews   setCreatedAt()  Sets the current record's "created_at" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReviews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reviews');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('bandid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('band', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('trackname', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('mp3', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('albumname', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('track', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('image', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}