<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin', 'doctrine');

/**
 * BaseAdmin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $userid
 * @property string $bandname
 * @property string $username
 * @property string $pwd
 * @property string $usergroup
 * @property string $address1
 * @property string $address2
 * @property string $city
 * @property string $state_province
 * @property string $zip_postal
 * @property string $genre
 * @property timestamp $created_at
 * 
 * @method integer   getUserid()         Returns the current record's "userid" value
 * @method string    getBandname()       Returns the current record's "bandname" value
 * @method string    getUsername()       Returns the current record's "username" value
 * @method string    getPwd()            Returns the current record's "pwd" value
 * @method string    getUsergroup()      Returns the current record's "usergroup" value
 * @method string    getAddress1()       Returns the current record's "address1" value
 * @method string    getAddress2()       Returns the current record's "address2" value
 * @method string    getCity()           Returns the current record's "city" value
 * @method string    getStateProvince()  Returns the current record's "state_province" value
 * @method string    getZipPostal()      Returns the current record's "zip_postal" value
 * @method string    getGenre()          Returns the current record's "genre" value
 * @method timestamp getCreatedAt()      Returns the current record's "created_at" value
 * @method Admin     setUserid()         Sets the current record's "userid" value
 * @method Admin     setBandname()       Sets the current record's "bandname" value
 * @method Admin     setUsername()       Sets the current record's "username" value
 * @method Admin     setPwd()            Sets the current record's "pwd" value
 * @method Admin     setUsergroup()      Sets the current record's "usergroup" value
 * @method Admin     setAddress1()       Sets the current record's "address1" value
 * @method Admin     setAddress2()       Sets the current record's "address2" value
 * @method Admin     setCity()           Sets the current record's "city" value
 * @method Admin     setStateProvince()  Sets the current record's "state_province" value
 * @method Admin     setZipPostal()      Sets the current record's "zip_postal" value
 * @method Admin     setGenre()          Sets the current record's "genre" value
 * @method Admin     setCreatedAt()      Sets the current record's "created_at" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdmin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('admin');
        $this->hasColumn('userid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('bandname', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('username', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('pwd', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('usergroup', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('address1', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('address2', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('city', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('state_province', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('zip_postal', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('genre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}