<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblLabel', 'doctrine');

/**
 * BaseTblLabel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $userid
 * @property string $labelname
 * @property string $username
 * @property string $pwd
 * @property string $usergroup
 * @property string $address1
 * @property string $address2
 * @property string $city
 * @property string $state_province
 * @property string $zip_postal
 * @property string $numbands
 * 
 * @method integer  getUserid()         Returns the current record's "userid" value
 * @method string   getLabelname()      Returns the current record's "labelname" value
 * @method string   getUsername()       Returns the current record's "username" value
 * @method string   getPwd()            Returns the current record's "pwd" value
 * @method string   getUsergroup()      Returns the current record's "usergroup" value
 * @method string   getAddress1()       Returns the current record's "address1" value
 * @method string   getAddress2()       Returns the current record's "address2" value
 * @method string   getCity()           Returns the current record's "city" value
 * @method string   getStateProvince()  Returns the current record's "state_province" value
 * @method string   getZipPostal()      Returns the current record's "zip_postal" value
 * @method string   getNumbands()       Returns the current record's "numbands" value
 * @method TblLabel setUserid()         Sets the current record's "userid" value
 * @method TblLabel setLabelname()      Sets the current record's "labelname" value
 * @method TblLabel setUsername()       Sets the current record's "username" value
 * @method TblLabel setPwd()            Sets the current record's "pwd" value
 * @method TblLabel setUsergroup()      Sets the current record's "usergroup" value
 * @method TblLabel setAddress1()       Sets the current record's "address1" value
 * @method TblLabel setAddress2()       Sets the current record's "address2" value
 * @method TblLabel setCity()           Sets the current record's "city" value
 * @method TblLabel setStateProvince()  Sets the current record's "state_province" value
 * @method TblLabel setZipPostal()      Sets the current record's "zip_postal" value
 * @method TblLabel setNumbands()       Sets the current record's "numbands" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblLabel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_label');
        $this->hasColumn('userid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('labelname', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('username', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('pwd', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('usergroup', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('address1', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('address2', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('city', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('state_province', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('zip_postal', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('numbands', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}