<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvClubDetails', 'doctrine');

/**
 * BaseTvClubDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $club_id
 * @property string $name
 * @property integer $capacity
 * @property integer $sq_feet
 * @property string $comments
 * @property timestamp $created_at
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method integer       getClubId()     Returns the current record's "club_id" value
 * @method string        getName()       Returns the current record's "name" value
 * @method integer       getCapacity()   Returns the current record's "capacity" value
 * @method integer       getSqFeet()     Returns the current record's "sq_feet" value
 * @method string        getComments()   Returns the current record's "comments" value
 * @method timestamp     getCreatedAt()  Returns the current record's "created_at" value
 * @method TvClubDetails setId()         Sets the current record's "id" value
 * @method TvClubDetails setClubId()     Sets the current record's "club_id" value
 * @method TvClubDetails setName()       Sets the current record's "name" value
 * @method TvClubDetails setCapacity()   Sets the current record's "capacity" value
 * @method TvClubDetails setSqFeet()     Sets the current record's "sq_feet" value
 * @method TvClubDetails setComments()   Sets the current record's "comments" value
 * @method TvClubDetails setCreatedAt()  Sets the current record's "created_at" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvClubDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_club_details');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('club_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('capacity', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sq_feet', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comments', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}