<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvItunesArtistImg', 'doctrine');

/**
 * BaseTvItunesArtistImg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $artist_id
 * @property string $img
 * @property string $lg_img
 * 
 * @method integer           getId()        Returns the current record's "id" value
 * @method integer           getArtistId()  Returns the current record's "artist_id" value
 * @method string            getImg()       Returns the current record's "img" value
 * @method string            getLgImg()     Returns the current record's "lg_img" value
 * @method TvItunesArtistImg setId()        Sets the current record's "id" value
 * @method TvItunesArtistImg setArtistId()  Sets the current record's "artist_id" value
 * @method TvItunesArtistImg setImg()       Sets the current record's "img" value
 * @method TvItunesArtistImg setLgImg()     Sets the current record's "lg_img" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvItunesArtistImg extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_itunes_artist_img');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('artist_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('img', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lg_img', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}