<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvTourManagement', 'doctrine');

/**
 * BaseTvTourManagement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $agent_id
 * @property integer $artist_id
 * @property string $artist_name
 * @property string $tour_management_name
 * @property string $tour_management_phone
 * @property string $tour_management_email
 * @property string $tour_management_mobile
 * @property string $tour_name
 * @property integer $tour_id
 * 
 * @method integer          getId()                     Returns the current record's "id" value
 * @method integer          getAgentId()                Returns the current record's "agent_id" value
 * @method integer          getArtistId()               Returns the current record's "artist_id" value
 * @method string           getArtistName()             Returns the current record's "artist_name" value
 * @method string           getTourManagementName()     Returns the current record's "tour_management_name" value
 * @method string           getTourManagementPhone()    Returns the current record's "tour_management_phone" value
 * @method string           getTourManagementEmail()    Returns the current record's "tour_management_email" value
 * @method string           getTourManagementMobile()   Returns the current record's "tour_management_mobile" value
 * @method string           getTourName()               Returns the current record's "tour_name" value
 * @method integer          getTourId()                 Returns the current record's "tour_id" value
 * @method TvTourManagement setId()                     Sets the current record's "id" value
 * @method TvTourManagement setAgentId()                Sets the current record's "agent_id" value
 * @method TvTourManagement setArtistId()               Sets the current record's "artist_id" value
 * @method TvTourManagement setArtistName()             Sets the current record's "artist_name" value
 * @method TvTourManagement setTourManagementName()     Sets the current record's "tour_management_name" value
 * @method TvTourManagement setTourManagementPhone()    Sets the current record's "tour_management_phone" value
 * @method TvTourManagement setTourManagementEmail()    Sets the current record's "tour_management_email" value
 * @method TvTourManagement setTourManagementMobile()   Sets the current record's "tour_management_mobile" value
 * @method TvTourManagement setTourName()               Sets the current record's "tour_name" value
 * @method TvTourManagement setTourId()                 Sets the current record's "tour_id" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvTourManagement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_tour_management');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('agent_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '4',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('artist_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('artist_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('tour_management_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('tour_management_phone', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tour_management_email', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('tour_management_mobile', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tour_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('tour_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}