<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NewClub', 'doctrine');

/**
 * BaseNewClub
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ps_id
 * @property string $name
 * @property string $slug
 * @property string $address
 * @property string $city
 * @property string $state
 * @property string $zip
 * @property string $country
 * @property string $url
 * 
 * @method integer getId()      Returns the current record's "id" value
 * @method integer getPsId()    Returns the current record's "ps_id" value
 * @method string  getName()    Returns the current record's "name" value
 * @method string  getSlug()    Returns the current record's "slug" value
 * @method string  getAddress() Returns the current record's "address" value
 * @method string  getCity()    Returns the current record's "city" value
 * @method string  getState()   Returns the current record's "state" value
 * @method string  getZip()     Returns the current record's "zip" value
 * @method string  getCountry() Returns the current record's "country" value
 * @method string  getUrl()     Returns the current record's "url" value
 * @method NewClub setId()      Sets the current record's "id" value
 * @method NewClub setPsId()    Sets the current record's "ps_id" value
 * @method NewClub setName()    Sets the current record's "name" value
 * @method NewClub setSlug()    Sets the current record's "slug" value
 * @method NewClub setAddress() Sets the current record's "address" value
 * @method NewClub setCity()    Sets the current record's "city" value
 * @method NewClub setState()   Sets the current record's "state" value
 * @method NewClub setZip()     Sets the current record's "zip" value
 * @method NewClub setCountry() Sets the current record's "country" value
 * @method NewClub setUrl()     Sets the current record's "url" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewClub extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('new_club');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ps_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('slug', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('address', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('state', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('zip', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('country', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('url', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}