<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvArtistAlbumImg', 'doctrine');

/**
 * BaseTvArtistAlbumImg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $artist_id
 * @property string $img
 * @property string $lg_img
 * @property timestamp $created_at
 * 
 * @method integer          getId()         Returns the current record's "id" value
 * @method integer          getArtistId()   Returns the current record's "artist_id" value
 * @method string           getImg()        Returns the current record's "img" value
 * @method string           getLgImg()      Returns the current record's "lg_img" value
 * @method timestamp        getCreatedAt()  Returns the current record's "created_at" value
 * @method TvArtistAlbumImg setId()         Sets the current record's "id" value
 * @method TvArtistAlbumImg setArtistId()   Sets the current record's "artist_id" value
 * @method TvArtistAlbumImg setImg()        Sets the current record's "img" value
 * @method TvArtistAlbumImg setLgImg()      Sets the current record's "lg_img" value
 * @method TvArtistAlbumImg setCreatedAt()  Sets the current record's "created_at" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvArtistAlbumImg extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_artist_album_img');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('artist_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('img', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lg_img', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}