<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvNewCityList', 'doctrine');

/**
 * BaseTvNewCityList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $city
 * @property string $state_abv
 * @property timestamp $created_at
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method string        getCity()       Returns the current record's "city" value
 * @method string        getStateAbv()   Returns the current record's "state_abv" value
 * @method timestamp     getCreatedAt()  Returns the current record's "created_at" value
 * @method TvNewCityList setId()         Sets the current record's "id" value
 * @method TvNewCityList setCity()       Sets the current record's "city" value
 * @method TvNewCityList setStateAbv()   Sets the current record's "state_abv" value
 * @method TvNewCityList setCreatedAt()  Sets the current record's "created_at" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvNewCityList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_new_city_list');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('state_abv', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}