<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvPromoter', 'doctrine');

/**
 * BaseTvPromoter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $promoter_id
 * @property integer $club_id
 * @property string $promoter_name
 * @property string $promoter_email
 * @property string $promoter_phone
 * @property string $promoter_fax
 * @property integer $active
 * @property timestamp $created_at
 * @property TvClub $TvClub
 * 
 * @method integer    getId()             Returns the current record's "id" value
 * @method integer    getPromoterId()     Returns the current record's "promoter_id" value
 * @method integer    getClubId()         Returns the current record's "club_id" value
 * @method string     getPromoterName()   Returns the current record's "promoter_name" value
 * @method string     getPromoterEmail()  Returns the current record's "promoter_email" value
 * @method string     getPromoterPhone()  Returns the current record's "promoter_phone" value
 * @method string     getPromoterFax()    Returns the current record's "promoter_fax" value
 * @method integer    getActive()         Returns the current record's "active" value
 * @method timestamp  getCreatedAt()      Returns the current record's "created_at" value
 * @method TvClub     getTvClub()         Returns the current record's "TvClub" value
 * @method TvPromoter setId()             Sets the current record's "id" value
 * @method TvPromoter setPromoterId()     Sets the current record's "promoter_id" value
 * @method TvPromoter setClubId()         Sets the current record's "club_id" value
 * @method TvPromoter setPromoterName()   Sets the current record's "promoter_name" value
 * @method TvPromoter setPromoterEmail()  Sets the current record's "promoter_email" value
 * @method TvPromoter setPromoterPhone()  Sets the current record's "promoter_phone" value
 * @method TvPromoter setPromoterFax()    Sets the current record's "promoter_fax" value
 * @method TvPromoter setActive()         Sets the current record's "active" value
 * @method TvPromoter setCreatedAt()      Sets the current record's "created_at" value
 * @method TvPromoter setTvClub()         Sets the current record's "TvClub" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvPromoter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_promoter');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('promoter_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '4',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('club_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '4',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('promoter_name', 'string', 125, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 125,
             ));
        $this->hasColumn('promoter_email', 'string', 125, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 125,
             ));
        $this->hasColumn('promoter_phone', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('promoter_fax', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('active', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TvClub', array(
             'local' => 'club_id',
             'foreign' => 'id'));
    }
}