<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SfCombine', 'doctrine');

/**
 * BaseSfCombine
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $assets_key
 * @property string $files
 * 
 * @method string    getAssetsKey()  Returns the current record's "assets_key" value
 * @method string    getFiles()      Returns the current record's "files" value
 * @method SfCombine setAssetsKey()  Sets the current record's "assets_key" value
 * @method SfCombine setFiles()      Sets the current record's "files" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSfCombine extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_combine');
        $this->hasColumn('assets_key', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('files', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}