<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvEmailQueueSend', 'doctrine');

/**
 * BaseTvEmailQueueSend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $email_id
 * @property string $email
 * @property integer $club_id
 * @property integer $promoter_id
 * @property integer $tour_id
 * @property string $body_html
 * @property string $body_plaintext
 * 
 * @method integer          getId()             Returns the current record's "id" value
 * @method integer          getEmailId()        Returns the current record's "email_id" value
 * @method string           getEmail()          Returns the current record's "email" value
 * @method integer          getClubId()         Returns the current record's "club_id" value
 * @method integer          getPromoterId()     Returns the current record's "promoter_id" value
 * @method integer          getTourId()         Returns the current record's "tour_id" value
 * @method string           getBodyHtml()       Returns the current record's "body_html" value
 * @method string           getBodyPlaintext()  Returns the current record's "body_plaintext" value
 * @method TvEmailQueueSend setId()             Sets the current record's "id" value
 * @method TvEmailQueueSend setEmailId()        Sets the current record's "email_id" value
 * @method TvEmailQueueSend setEmail()          Sets the current record's "email" value
 * @method TvEmailQueueSend setClubId()         Sets the current record's "club_id" value
 * @method TvEmailQueueSend setPromoterId()     Sets the current record's "promoter_id" value
 * @method TvEmailQueueSend setTourId()         Sets the current record's "tour_id" value
 * @method TvEmailQueueSend setBodyHtml()       Sets the current record's "body_html" value
 * @method TvEmailQueueSend setBodyPlaintext()  Sets the current record's "body_plaintext" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvEmailQueueSend extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_email_queue_send');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('email_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('club_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('promoter_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('tour_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('body_html', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('body_plaintext', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}