<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Prioritylist', 'doctrine');

/**
 * BasePrioritylist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $owner
 * @property blob $message
 * @property string $level
 * @property string $url
 * @property blob $status
 * @property date $date_start
 * @property date $ext_date_com
 * @property date $date_closed
 * 
 * @method integer      getId()           Returns the current record's "id" value
 * @method string       getOwner()        Returns the current record's "owner" value
 * @method blob         getMessage()      Returns the current record's "message" value
 * @method string       getLevel()        Returns the current record's "level" value
 * @method string       getUrl()          Returns the current record's "url" value
 * @method blob         getStatus()       Returns the current record's "status" value
 * @method date         getDateStart()    Returns the current record's "date_start" value
 * @method date         getExtDateCom()   Returns the current record's "ext_date_com" value
 * @method date         getDateClosed()   Returns the current record's "date_closed" value
 * @method Prioritylist setId()           Sets the current record's "id" value
 * @method Prioritylist setOwner()        Sets the current record's "owner" value
 * @method Prioritylist setMessage()      Sets the current record's "message" value
 * @method Prioritylist setLevel()        Sets the current record's "level" value
 * @method Prioritylist setUrl()          Sets the current record's "url" value
 * @method Prioritylist setStatus()       Sets the current record's "status" value
 * @method Prioritylist setDateStart()    Sets the current record's "date_start" value
 * @method Prioritylist setExtDateCom()   Sets the current record's "ext_date_com" value
 * @method Prioritylist setDateClosed()   Sets the current record's "date_closed" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrioritylist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('prioritylist');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('owner', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('message', 'blob', null, array(
             'type' => 'blob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('level', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('url', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('status', 'blob', null, array(
             'type' => 'blob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('date_start', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('ext_date_com', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('date_closed', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}