<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ReviewUsers', 'doctrine');

/**
 * BaseReviewUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $userid
 * @property string $user
 * @property integer $bandid
 * @property string $band
 * @property string $review
 * @property string $album
 * @property string $image
 * @property string $type
 * 
 * @method integer     getId()     Returns the current record's "id" value
 * @method integer     getUserid() Returns the current record's "userid" value
 * @method string      getUser()   Returns the current record's "user" value
 * @method integer     getBandid() Returns the current record's "bandid" value
 * @method string      getBand()   Returns the current record's "band" value
 * @method string      getReview() Returns the current record's "review" value
 * @method string      getAlbum()  Returns the current record's "album" value
 * @method string      getImage()  Returns the current record's "image" value
 * @method string      getType()   Returns the current record's "type" value
 * @method ReviewUsers setId()     Sets the current record's "id" value
 * @method ReviewUsers setUserid() Sets the current record's "userid" value
 * @method ReviewUsers setUser()   Sets the current record's "user" value
 * @method ReviewUsers setBandid() Sets the current record's "bandid" value
 * @method ReviewUsers setBand()   Sets the current record's "band" value
 * @method ReviewUsers setReview() Sets the current record's "review" value
 * @method ReviewUsers setAlbum()  Sets the current record's "album" value
 * @method ReviewUsers setImage()  Sets the current record's "image" value
 * @method ReviewUsers setType()   Sets the current record's "type" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReviewUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('review_users');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('userid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('user', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('bandid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('band', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('review', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('album', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('image', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('type', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}