<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvAgency', 'doctrine');

/**
 * BaseTvAgency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $address
 * @property string $city
 * @property string $state
 * @property integer $zip
 * @property string $country
 * @property string $phone
 * @property integer $artist_count
 * @property integer $agent_count
 * @property timestamp $created_at
 * @property Doctrine_Collection $TvAgentOffer
 * @property Doctrine_Collection $TvAgentRoster
 * @property Doctrine_Collection $TvAgents
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getAddress()       Returns the current record's "address" value
 * @method string              getCity()          Returns the current record's "city" value
 * @method string              getState()         Returns the current record's "state" value
 * @method integer             getZip()           Returns the current record's "zip" value
 * @method string              getCountry()       Returns the current record's "country" value
 * @method string              getPhone()         Returns the current record's "phone" value
 * @method integer             getArtistCount()   Returns the current record's "artist_count" value
 * @method integer             getAgentCount()    Returns the current record's "agent_count" value
 * @method timestamp           getCreatedAt()     Returns the current record's "created_at" value
 * @method Doctrine_Collection getTvAgentOffer()  Returns the current record's "TvAgentOffer" collection
 * @method Doctrine_Collection getTvAgentRoster() Returns the current record's "TvAgentRoster" collection
 * @method Doctrine_Collection getTvAgents()      Returns the current record's "TvAgents" collection
 * @method TvAgency            setId()            Sets the current record's "id" value
 * @method TvAgency            setName()          Sets the current record's "name" value
 * @method TvAgency            setAddress()       Sets the current record's "address" value
 * @method TvAgency            setCity()          Sets the current record's "city" value
 * @method TvAgency            setState()         Sets the current record's "state" value
 * @method TvAgency            setZip()           Sets the current record's "zip" value
 * @method TvAgency            setCountry()       Sets the current record's "country" value
 * @method TvAgency            setPhone()         Sets the current record's "phone" value
 * @method TvAgency            setArtistCount()   Sets the current record's "artist_count" value
 * @method TvAgency            setAgentCount()    Sets the current record's "agent_count" value
 * @method TvAgency            setCreatedAt()     Sets the current record's "created_at" value
 * @method TvAgency            setTvAgentOffer()  Sets the current record's "TvAgentOffer" collection
 * @method TvAgency            setTvAgentRoster() Sets the current record's "TvAgentRoster" collection
 * @method TvAgency            setTvAgents()      Sets the current record's "TvAgents" collection
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvAgency extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_agency');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('address', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('city', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('state', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('zip', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('country', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('phone', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('artist_count', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('agent_count', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TvAgentOffer', array(
             'local' => 'id',
             'foreign' => 'agency_id'));

        $this->hasMany('TvAgentRoster', array(
             'local' => 'id',
             'foreign' => 'agency_id'));

        $this->hasMany('TvAgents', array(
             'local' => 'id',
             'foreign' => 'agency_id'));
    }
}