<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvActionTracking', 'doctrine');

/**
 * BaseTvActionTracking
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $trackaction
 * @property integer $trackcount
 * @property date $trackdate
 * 
 * @method integer          getId()          Returns the current record's "id" value
 * @method string           getTrackaction() Returns the current record's "trackaction" value
 * @method integer          getTrackcount()  Returns the current record's "trackcount" value
 * @method date             getTrackdate()   Returns the current record's "trackdate" value
 * @method TvActionTracking setId()          Sets the current record's "id" value
 * @method TvActionTracking setTrackaction() Sets the current record's "trackaction" value
 * @method TvActionTracking setTrackcount()  Sets the current record's "trackcount" value
 * @method TvActionTracking setTrackdate()   Sets the current record's "trackdate" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvActionTracking extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_action_tracking');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('trackaction', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('trackcount', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('trackdate', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}