<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvItunesArtist', 'doctrine');

/**
 * BaseTvItunesArtist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $artist_id
 * @property integer $tv_id
 * @property string $genre
 * @property string $artist_name
 * @property string $bio
 * @property string $itunes_url
 * 
 * @method integer        getId()          Returns the current record's "id" value
 * @method integer        getArtistId()    Returns the current record's "artist_id" value
 * @method integer        getTvId()        Returns the current record's "tv_id" value
 * @method string         getGenre()       Returns the current record's "genre" value
 * @method string         getArtistName()  Returns the current record's "artist_name" value
 * @method string         getBio()         Returns the current record's "bio" value
 * @method string         getItunesUrl()   Returns the current record's "itunes_url" value
 * @method TvItunesArtist setId()          Sets the current record's "id" value
 * @method TvItunesArtist setArtistId()    Sets the current record's "artist_id" value
 * @method TvItunesArtist setTvId()        Sets the current record's "tv_id" value
 * @method TvItunesArtist setGenre()       Sets the current record's "genre" value
 * @method TvItunesArtist setArtistName()  Sets the current record's "artist_name" value
 * @method TvItunesArtist setBio()         Sets the current record's "bio" value
 * @method TvItunesArtist setItunesUrl()   Sets the current record's "itunes_url" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvItunesArtist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_itunes_artist');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('artist_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('tv_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('genre', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('artist_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('bio', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('itunes_url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}