<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvEmailQueueAvails', 'doctrine');

/**
 * BaseTvEmailQueueAvails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $agent_id
 * @property integer $artist_id
 * @property integer $tour_id
 * @property integer $sent
 * @property string $text_area
 * @property string $additional_text
 * @property timestamp $created_at
 * 
 * @method integer            getId()              Returns the current record's "id" value
 * @method integer            getAgentId()         Returns the current record's "agent_id" value
 * @method integer            getArtistId()        Returns the current record's "artist_id" value
 * @method integer            getTourId()          Returns the current record's "tour_id" value
 * @method integer            getSent()            Returns the current record's "sent" value
 * @method string             getTextArea()        Returns the current record's "text_area" value
 * @method string             getAdditionalText()  Returns the current record's "additional_text" value
 * @method timestamp          getCreatedAt()       Returns the current record's "created_at" value
 * @method TvEmailQueueAvails setId()              Sets the current record's "id" value
 * @method TvEmailQueueAvails setAgentId()         Sets the current record's "agent_id" value
 * @method TvEmailQueueAvails setArtistId()        Sets the current record's "artist_id" value
 * @method TvEmailQueueAvails setTourId()          Sets the current record's "tour_id" value
 * @method TvEmailQueueAvails setSent()            Sets the current record's "sent" value
 * @method TvEmailQueueAvails setTextArea()        Sets the current record's "text_area" value
 * @method TvEmailQueueAvails setAdditionalText()  Sets the current record's "additional_text" value
 * @method TvEmailQueueAvails setCreatedAt()       Sets the current record's "created_at" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvEmailQueueAvails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_email_queue_avails');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('agent_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('artist_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('tour_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('sent', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('text_area', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('additional_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}