<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Labels', 'doctrine');

/**
 * BaseLabels
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $labels
 * @property string $daemail
 * @property string $url
 * 
 * @method integer getId()      Returns the current record's "id" value
 * @method string  getLabels()  Returns the current record's "labels" value
 * @method string  getDaemail() Returns the current record's "daemail" value
 * @method string  getUrl()     Returns the current record's "url" value
 * @method Labels  setId()      Sets the current record's "id" value
 * @method Labels  setLabels()  Sets the current record's "labels" value
 * @method Labels  setDaemail() Sets the current record's "daemail" value
 * @method Labels  setUrl()     Sets the current record's "url" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLabels extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('labels');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('labels', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('daemail', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('url', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}