<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvPsCityIds', 'doctrine');

/**
 * BaseTvPsCityIds
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $city_id
 * @property string $city_name
 * @property string $state_abv
 * @property float $latitude
 * @property float $longitude
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method integer     getCityId()    Returns the current record's "city_id" value
 * @method string      getCityName()  Returns the current record's "city_name" value
 * @method string      getStateAbv()  Returns the current record's "state_abv" value
 * @method float       getLatitude()  Returns the current record's "latitude" value
 * @method float       getLongitude() Returns the current record's "longitude" value
 * @method TvPsCityIds setId()        Sets the current record's "id" value
 * @method TvPsCityIds setCityId()    Sets the current record's "city_id" value
 * @method TvPsCityIds setCityName()  Sets the current record's "city_name" value
 * @method TvPsCityIds setStateAbv()  Sets the current record's "state_abv" value
 * @method TvPsCityIds setLatitude()  Sets the current record's "latitude" value
 * @method TvPsCityIds setLongitude() Sets the current record's "longitude" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvPsCityIds extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_ps_city_ids');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('city_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('city_name', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('state_abv', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('latitude', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '-1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('longitude', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '-1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}