<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvArtistMp3', 'doctrine');

/**
 * BaseTvArtistMp3
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $artist_id
 * @property string $title
 * @property string $mp3
 * @property timestamp $created_at
 * @property TvArtist $TvArtist
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method integer     getArtistId()   Returns the current record's "artist_id" value
 * @method string      getTitle()      Returns the current record's "title" value
 * @method string      getMp3()        Returns the current record's "mp3" value
 * @method timestamp   getCreatedAt()  Returns the current record's "created_at" value
 * @method TvArtist    getTvArtist()   Returns the current record's "TvArtist" value
 * @method TvArtistMp3 setId()         Sets the current record's "id" value
 * @method TvArtistMp3 setArtistId()   Sets the current record's "artist_id" value
 * @method TvArtistMp3 setTitle()      Sets the current record's "title" value
 * @method TvArtistMp3 setMp3()        Sets the current record's "mp3" value
 * @method TvArtistMp3 setCreatedAt()  Sets the current record's "created_at" value
 * @method TvArtistMp3 setTvArtist()   Sets the current record's "TvArtist" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvArtistMp3 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_artist_mp3');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('artist_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '4',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('mp3', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TvArtist', array(
             'local' => 'artist_id',
             'foreign' => 'id'));
    }
}