<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvApiCount', 'doctrine');

/**
 * BaseTvApiCount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $api_id
 * @property integer $api_count
 * @property integer $api_type
 * 
 * @method integer    getId()        Returns the current record's "id" value
 * @method integer    getApiId()     Returns the current record's "api_id" value
 * @method integer    getApiCount()  Returns the current record's "api_count" value
 * @method integer    getApiType()   Returns the current record's "api_type" value
 * @method TvApiCount setId()        Sets the current record's "id" value
 * @method TvApiCount setApiId()     Sets the current record's "api_id" value
 * @method TvApiCount setApiCount()  Sets the current record's "api_count" value
 * @method TvApiCount setApiType()   Sets the current record's "api_type" value
 * 
 * @package    tourvolume
 * @subpackage model
 * @author     Dave Bonillas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvApiCount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_api_count');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('api_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('api_count', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('api_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}