<?php

/**
 * ApiCountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApiCountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApiCountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApiCount');
    }
}