<?php

/**
 * ApiTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApiTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApiTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApiType');
    }
}