<?php

/**
 * BandsOnTourTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BandsOnTourTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BandsOnTourTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BandsOnTour');
    }
}