<?php

/**
 * BandsOnLabelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BandsOnLabelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BandsOnLabelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BandsOnLabel');
    }
}