<?php

/**
 * BandblogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BandblogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BandblogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bandblog');
    }
}