<?php

/**
 * BattleSubmissionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BattleSubmissionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BattleSubmissionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BattleSubmissions');
    }
}