<?php

/**
 * BestofTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BestofTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BestofTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bestof');
    }
}