<?php

/**
 * ClubaccessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClubaccessTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClubaccessTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clubaccess');
    }
}