<?php

/**
 * CommentsUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentsUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentsUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CommentsUser');
    }
}