<?php

/**
 * LabelContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LabelContactsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LabelContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LabelContacts');
    }
}