<?php

/**
 * LabelsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LabelsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LabelsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Labels');
    }
}