<?php

/**
 * NewBandsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewBandsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewBandsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewBands');
    }
}