<?php

/**
 * NewsfeedsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsfeedsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsfeedsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Newsfeeds');
    }
}