<?php

/**
 * OldTvCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OldTvCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OldTvCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OldTvCity');
    }
}