<?php

/**
 * PrioritylistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrioritylistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrioritylistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Prioritylist');
    }
}