<?php

/**
 * ReviewCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReviewCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReviewCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReviewComments');
    }
}