<?php

/**
 * ReviewCopyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReviewCopyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReviewCopyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReviewCopy');
    }
}