<?php

/**
 * ReviewUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReviewUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReviewUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReviewUsers');
    }
}