<?php

/**
 * ReviewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReviewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReviewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reviews');
    }
}