<?php

/**
 * TblClubTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblClubTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblClubTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblClub');
    }
}