<?php

/**
 * TblLabelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblLabelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblLabelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblLabel');
    }
}