<?php

/**
 * TblUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblUsers');
    }
}