<?php

/**
 * TourDataSetupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TourDataSetupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TourDataSetupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TourDataSetup');
    }
}