<?php

/**
 * TvActionTrackingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvActionTrackingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvActionTrackingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvActionTracking');
    }
}