<?php

/**
 * TvAdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvAdminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvAdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvAdmin');
    }
}