<?php

/**
 * TvAgentRosterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvAgentRosterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvAgentRosterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvAgentRoster');
    }
}