<?php

/**
 * TvAgentOfferTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvAgentOfferTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvAgentOfferTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvAgentOffer');
    }
}