<?php

/**
 * TvAllCitiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvAllCitiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvAllCitiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvAllCities');
    }
}