<?php

/**
 * TvApiTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvApiTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvApiTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvApiType');
    }
}