<?php

/**
 * TvArtistAlbumImgTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvArtistAlbumImgTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvArtistAlbumImgTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvArtistAlbumImg');
    }
}