<?php

/**
 * TvArtistMp3Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvArtistMp3Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvArtistMp3Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvArtistMp3');
    }
}