<?php

/**
 * TvArtistRelatedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvArtistRelatedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvArtistRelatedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvArtistRelated');
    }
}