<?php

/**
 * TvCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvCityTable
     */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('TvCity');
  }

  public function autoSearch($a)
  {
    $q = $this->createQuery('c')
    ->where('c.city LIKE ?', $a.'%')
    ->limit(5);
    return $q->execute();
  }
  public function getCityObj($city, $state)
  {
    $q = $this->createQuery('c')
    ->where('c.city = ?', $city)
    ->andWhere('c.state = ?', $state);
    return $q->fetchOne();
  }
}