<?php

/**
 * TvClubCopyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvClubCopyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvClubCopyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvClubCopy');
    }
}