<?php

/**
 * TvClubTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvClubTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object TvClubTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('TvClub');
  }

  public function autoSearch($a)
  {
    $q = $this->createQuery('c')
    ->where('c.name LIKE ?', $a.'%')
    ->limit(5);
    return $q->execute();
  }
}