<?php

/**
 * TvClubTicketsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvClubTicketsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvClubTicketsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvClubTickets');
    }
}