<?php

/**
 * TvClubTestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvClubTestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvClubTestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvClubTest');
    }
}