<?php

/**
 * TvClubPromoterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvClubPromoterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvClubPromoterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvClubPromoter');
    }
}