<?php

/**
 * TvClubDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvClubDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvClubDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvClubDetails');
    }
}