<?php

/**
 * TvConcertsHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvConcertsHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvConcertsHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvConcertsHistory');
    }
}