<?php

/**
 * TvConcertsImportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvConcertsImportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvConcertsImportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvConcertsImport');
    }
}