<?php

/**
 * TvConcertsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvConcertsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvConcertsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvConcerts');
    }
}