<?php

/**
 * TvConcertgoerFriendsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvConcertgoerFriendsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvConcertgoerFriendsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvConcertgoerFriends');
    }
}