<?php

/**
 * TvConcertgoerBandsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvConcertgoerBandsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvConcertgoerBandsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvConcertgoerBands');
    }
}