<?php

/**
 * TvConcertsSharedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvConcertsSharedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvConcertsSharedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvConcertsShared');
    }
}