<?php

/**
 * TvEmailQueueFailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvEmailQueueFailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvEmailQueueFailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvEmailQueueFail');
    }
}