<?php

/**
 * TvEmailQueueSendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvEmailQueueSendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvEmailQueueSendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvEmailQueueSend');
    }
}