<?php

/**
 * TvItunesArtistImgTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvItunesArtistImgTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvItunesArtistImgTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvItunesArtistImg');
    }
}