<?php

/**
 * TvItunesArtistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvItunesArtistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvItunesArtistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvItunesArtist');
    }
}