<?php

/**
 * TvLabelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvLabelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvLabelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvLabel');
    }
}