<?php

/**
 * TvLabelRosterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvLabelRosterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvLabelRosterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvLabelRoster');
    }
}