<?php

/**
 * TvNewCityListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvNewCityListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvNewCityListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvNewCityList');
    }
}