<?php

/**
 * TvOfferMessagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvOfferMessagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvOfferMessagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvOfferMessages');
    }
}