<?php

/**
 * TvPromoterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvPromoterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvPromoterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvPromoter');
    }
}