<?php

/**
 * TvPromoterCopyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvPromoterCopyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvPromoterCopyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvPromoterCopy');
    }
}