<?php

/**
 * TvTestPromoterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvTestPromoterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvTestPromoterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvTestPromoter');
    }
}