<?php

/**
 * TvTourManagementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvTourManagementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvTourManagementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvTourManagement');
    }
}