<?php

/**
 * TvTrackingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvTrackingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvTrackingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvTracking');
    }
}