<?php

/**
 * TvZipCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvZipCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvZipCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvZipCode');
    }
}