# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main,/sfJqueryReloadedPlugin/css/jquery-ui-1.8.13.custom.css, concert_listings, artist]

  javascripts:    [jquery.js, jquery-ui.js, jquery.jqpageflow.js, soundmanager2-nodebug.js, AC_QuickTime.js, player.js]

  has_layout:     true
  layout:         layout

